---
Name: subsite-multilogin
After:
  - 'framework/*'
  - 'cms/*'
---
Injector:
  MemberLoginForm:
    class: SubsiteMemberLoginForm

SubsiteDomain:
  extensions:
    - SubsiteDomainExtension

SubsiteLogin_Controller:
  url_segment: "subsitelogin"